include:
 - salsa-ci.yml
 - pipeline-jobs.yml

variables:
    RELEASE: 'stretch-backports'

stages:
    - clone
    - build
    - test
    - test-backwards

clone:
    stage: clone
    image: debian:unstable
    before_script:
        - echo "I need to skip before_script"
    artifacts:
      paths:
          - repo_test
    script:
        - apt-get update && apt-get install git -y
        - git clone https://salsa.debian.org/salsa-ci-team/dummypackage repo_test

before_script:
    - cd repo_test

# Backwards compat tests

.dry: &dry
    before_script:
        - cd repo_test
    stage: test-backwards
    
build-unstable:
    extends: .build-unstable
    <<: *dry
    dependencies:
        - clone

build-stretch-backports:
    extends: .build-stretch-bpo
    <<: *dry
    dependencies:
        - clone

build-stretch:
    extends: .build-stretch
    <<: *dry
    dependencies:
        - clone

build-jessie:
    extends: .build-jessie
    <<: *dry
    dependencies:
        - clone

lintian-unstable:
    extends: .test-lintian-unstable
    <<: *dry

lintian-stretch-backports:
    extends: .test-lintian-stretch-backports
    <<: *dry

lintian-stretch:
    extends: .test-lintian-stretch
    <<: *dry

lintian-jessie:
    extends: .test-lintian-jessie
    <<: *dry
