include: salsa-ci.yml

stages:
    - clone
    - build
    - test

clone:
    stage: clone
    image: debian:unstable
    artifacts:
      paths:
          - ./
    script:
        - apt-get update && apt-get install git -y
        - git clone https://salsa.debian.org/ina-guest/test1.git tmp
        - rm -rf .git && mv tmp/.git . && rm -rf tmp && git reset --hard && git clean -fd

before_script:
    - rm -f .gitlab-ci.yml README.md pipeline_loader.py repositories.py salsa-ci-example.yml salsa-ci.yml salsa-pipeline-bot.py

build:
    extends: .build-unstable

reprotest:
    extends: .test-reprotest

lintian:
    extends: .test-lintian

autopkgtest:
    extends: .test-autopkgtest

piuparts:
    extends: .test-piuparts
