image: registry.salsa.debian.org/salsa-ci-team/images/pipeline

run:
  before_script:
    - git config --global user.name "Salsa Pipeline Bot"
    - git config --global user.email "salsa-pipeline@debian.org"
    - echo -e "machine salsa.debian.org\nlogin salsa-pipeline-guest\npassword ${SALSA_PIPELINE_PASSWORD}" > ~/.netrc
  script:
    - python3 salsa-pipeline-bot.py
  only: 
    - ${SALSA_TOKEN} && ${SALSA_PIPELINE_PASSWORD}
