# Copyright salsa-ci-team and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.

include:
 - .images-ci.yml
 - .images-debian.yml
 - .pipeline-test.yml

variables:
  DOCKER_TLS_CERTDIR: ""
  SALSA_CI_IMAGES_APTLY: ${CI_REGISTRY_IMAGE}/aptly:${CI_PIPELINE_ID}-latest
  SALSA_CI_IMAGES_AUTOPKGTEST: ${CI_REGISTRY_IMAGE}/autopkgtest:${CI_PIPELINE_ID}-latest
  SALSA_CI_IMAGES_BASE: ${CI_REGISTRY_IMAGE}/base:${CI_PIPELINE_ID}-${RELEASE}
  SALSA_CI_IMAGES_GENERIC_TESTS: ${CI_REGISTRY_IMAGE}/generic_tests:${CI_PIPELINE_ID}-${RELEASE}
  SALSA_CI_IMAGES_BLHC: ${CI_REGISTRY_IMAGE}/blhc:${CI_PIPELINE_ID}-latest
  SALSA_CI_IMAGES_DOCKERBUILDER: ${CI_REGISTRY_IMAGE}/dockerbuilder:${CI_PIPELINE_ID}-${RELEASE}
  SALSA_CI_IMAGES_GBP: ${CI_REGISTRY_IMAGE}/gbp:${CI_PIPELINE_ID}-latest
  SALSA_CI_IMAGES_LINTIAN: ${CI_REGISTRY_IMAGE}/lintian:${CI_PIPELINE_ID}-${RELEASE}
  SALSA_CI_IMAGES_PIUPARTS: ${CI_REGISTRY_IMAGE}/piuparts:${CI_PIPELINE_ID}-latest
  SALSA_CI_IMAGES_REPROTEST: ${CI_REGISTRY_IMAGE}/reprotest:${CI_PIPELINE_ID}-latest
  SALSA_CI_DISABLE_APTLY: "false"

stages:
  - prerequisites
  - images_base
  - images_others
  - build
  - publish
  - test
  - cleanup
  - contributions
  - deploy
