include: salsa-ci.yml

stages:
    - clone
    - build
    - test

clone:
    stage: clone
    image: debian:unstable
    before_script:
        - echo "I need to skip before_script"
    artifacts:
      paths:
          - repo_test
    script:
        - apt-get update && apt-get install git -y
        - git clone https://salsa.debian.org/salsa-ci-team/dummypackage repo_test

before_script:
    - cd repo_test

build:
    extends: .build-unstable

reprotest:
    extends: .test-reprotest

reprotest-diffoscope:
    extends: .test-reprotest-diffoscope

lintian:
    extends: .test-lintian

autopkgtest:
    extends: .test-autopkgtest

piuparts:
    extends: .test-piuparts
