image: registry.salsa.debian.org/salsa-ci-team/images/pipeline

run:
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan salsa.debian.org >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.name "Salsa Pipeline Bot"
    - git config --global user.email "salsa-pipeline@debian.org"
    - echo -e "machine salsa.debian.org\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
  script:
    - python3 salsa-pipeline-bot.py
  only: 
    - master
