image: debian:unstable

run:
  before_script:
    - apt-get update && apt-get install -y python3 python3-gitlab openssh-client git
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan salsa.debian.org >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - python3 salsa-pipeline-bot.py
  only: 
    - master
