# Copyright salsa-ci-team and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.

.should_build_images: &should_build_images
  only:
    changes:
      - images/**/*
      - .images-*.yml

.build_template: &build_template
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - cd ${CI_PROJECT_DIR}/images
  script:
    - IMAGE="${IMAGE:-$CI_JOB_NAME}"
    - NAME=$(echo $IMAGE | awk -F':' '{ print $1 }')
    - RELEASE=$(echo $IMAGE | awk -F':' '{ print $2 }')
    - VENDOR=${VENDOR:-debian}
    - BASE_IMAGE_NAME=${BASE_IMAGE_NAME:-${VENDOR}}
    - BASE_IMAGE_RELEASE=${BASE_IMAGE_RELEASE:-${RELEASE}}
    - |
        if [ "${CI_COMMIT_REF_NAME}" != "master" ]; then
            STAGING_TAG=_${CI_COMMIT_SHORT_SHA}
            IMAGE=${IMAGE}${STAGING_TAG}
        fi
    - |
        docker build --pull -t $CI_REGISTRY_IMAGE/$IMAGE \
            --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE \
            --build-arg VENDOR=$VENDOR \
            --build-arg RELEASE=$RELEASE \
            --build-arg BASE_IMAGE_NAME=$BASE_IMAGE_NAME \
            --build-arg BASE_IMAGE_RELEASE=$BASE_IMAGE_RELEASE \
            --build-arg STAGING_TAG=$STAGING_TAG \
            -f dockerfiles/$NAME .
    - |
        docker push $CI_REGISTRY_IMAGE/$IMAGE
        if [ "$VENDOR" = "debian" ]; then
            ALIASES=$(wget -O - http://deb.debian.org/debian/dists/$BASE_IMAGE_RELEASE/Release | grep ^Suite: | awk '{ print $2 }')
            test "$ALIASES" != 'unstable' || ALIASES="${ALIASES} latest"
        fi
        for alias in $ALIASES; do
            docker tag $CI_REGISTRY_IMAGE/$IMAGE $CI_REGISTRY_IMAGE/$NAME:$alias${STAGING_TAG}
            docker push $CI_REGISTRY_IMAGE/$NAME:$alias${STAGING_TAG}
        done
  <<: *should_build_images

clean images:
  stage: cleanup
  image: debian:unstable
  before_script:
    - apt-get update && apt-get install curl -y
  variables:
      REF_NAME: "master"
  script:
    - |
        if [ -n "${SALSA_CI_TRIGGER_CLEANUP_URL}" ]; then \
            curl -X POST \
             -F "token=$GARBAGE_COLLECTOR_TRIGGER_TOKEN" \
             -F "ref=$REF_NAME" \
             -F "variables[GIT_SHA]=${CI_COMMIT_SHORT_SHA}" \
             -F "variables[IMAGES_PROJECT_ID]=${CI_PROJECT_ID}" \
             ${SALSA_CI_TRIGGER_CLEANUP_URL} ; \
        else \
            echo "WARNING: No trigger URL configured."; \
        fi
  except:
    - master
  when: always
  <<: *should_build_images

.build_base: &build_base
  <<: *build_template
  stage: images_base

.build_others: &build_others
  <<: *build_template
  stage: images_others
