# Copyright salsa-ci-team and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.

variables:
  SALSA_CI_TRIGGER_CLEANUP_URL: https://salsa.debian.org/api/v4/projects/36571/trigger/pipeline

base:jessie:
  extends: .build_base
  variables:
    EXTRA_BUILD_ARGS: "--ulimit nofile=1024:1024"

base:stretch:
  extends: .build_base

base:stretch-backports:
  extends: .build_base

base:buster:
  extends: .build_base

base:buster-backports:
  extends: .build_base

base:bullseye:
  extends: .build_base

base:bullseye-backports:
  extends: .build_base

base:stable:
  extends: .build_base

base:unstable:
  extends: .build_base
  variables:
      ALIASES: 'latest'

base:experimental:
  extends: .build_base

base:testing:
  extends: .build_base

piuparts:unstable:
  extends: .build_others
  variables:
      ALIASES: 'latest'

reprotest:unstable:
  extends: .build_others
  variables:
      ALIASES: 'latest'

# Image for the pipeline runner
# salsa.debian.org/salsa-ci-team/pipeline
pipeline:unstable:
  extends: .build_others
  variables:
      ALIASES: 'latest'

autopkgtest:unstable:
  extends: .build_others
  variables:
      ALIASES: 'latest'

blhc:unstable:
  extends: .build_others
  variables:
      ALIASES: 'latest'

lintian:jessie:
  extends: .build_others
  variables:
    EXTRA_BUILD_ARGS: "--ulimit nofile=1024:1024"

lintian:stretch:
  extends: .build_others

lintian:stretch-backports:
  extends: .build_others

lintian:buster:
  extends: .build_others

lintian:bullseye:
  extends: .build_others

lintian:stable:
  extends: .build_others

lintian:unstable:
  extends: .build_others
  variables:
      ALIASES: 'latest'

lintian:experimental:
  extends: .build_others

lintian:testing:
  extends: .build_others

gbp:unstable:
  extends: .build_others
  variables:
      ALIASES: 'latest'

dockerbuilder:jessie:
  extends: .build_others
  variables:
    EXTRA_BUILD_ARGS: "--ulimit nofile=1024:1024"

dockerbuilder:stretch:
  extends: .build_others

dockerbuilder:stretch-backports:
  extends: .build_others

dockerbuilder:buster:
  extends: .build_others

dockerbuilder:bullseye:
  extends: .build_others

dockerbuilder:stable:
  extends: .build_others

dockerbuilder:unstable:
  extends: .build_others
  variables:
      ALIASES: 'latest'

dockerbuilder:experimental:
  extends: .build_others

dockerbuilder:testing:
  extends: .build_others

generic_tests:jessie:
  extends: .build_others
  variables:
    EXTRA_BUILD_ARGS: "--ulimit nofile=1024:1024"

generic_tests:stretch:
  extends: .build_others

generic_tests:stretch-backports:
  extends: .build_others

generic_tests:buster:
  extends: .build_others

generic_tests:buster-backports:
  extends: .build_others

generic_tests:bullseye:
  extends: .build_others

generic_tests:bullseye-backports:
  extends: .build_others

generic_tests:stable:
  extends: .build_others

generic_tests:unstable:
  extends: .build_others
  variables:
      ALIASES: 'latest'

generic_tests:experimental:
  extends: .build_others

generic_tests:testing:
  extends: .build_others
