# Copyright salsa-ci-team and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.

include:
 - .images-ci.yml

variables:
  VENDOR: debian
  RELEASE: sid

.build_only_sid: &build_only_sid
  extends: .build_template
  only:
    variables:
      - $RELEASE == 'sid'

#
# These images build only for sid.
#
image:aptly:
  extends: .build_only_sid

image:autopkgtest:
  extends: .build_only_sid

image:blhc:
  extends: .build_only_sid

image:piuparts:
  extends: .build_only_sid

image:reprotest:
  extends: .build_only_sid

#
# These images build for all the releases.
#
image:base:
  extends: .build_template

image:gbp:
  extends: .build_template

image:lintian:
  extends: .build_template
  only:
    variables:
      # Use != to avoid overriding template except.
      - $RELEASE != 'experimental'

image:generic_tests:
  extends: .build_template

#
# Trigger build of other releases.
#
trigger other releases:
  extends: .trigger_build
  variables:
    RELEASES_LIST: 'jessie stretch stretch-backports buster buster-backports bullseye bullseye-backports experimental'
