# Copyright salsa-ci-team and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.

include:
 - .images-ci.yml

variables:
  VENDOR: kali
  RELEASE: kali-dev
  BASE_IMAGE: "debian:testing"


.build_only_kali-dev: &build_only_kali-dev
  extends: .build_template
  only:
    variables:
      - $RELEASE == 'kali-dev'

.build_except_kali-experimental: &build_except_kali-experimental
  extends: .build_template
  except:
    variables:
      - $RELEASE == 'kali-experimental'

image:base:
  extends: .build_template

image:piuparts:
  extends: .build_only_kali-dev

image:reprotest:
  extends: .build_only_kali-dev

image:autopkgtest:
  extends: .build_only_kali-dev

image:blhc:
  extends: .build_only_kali-dev

image:lintian:
  extends: .build_except_kali-experimental

image:gbp:
  extends: .build_only_kali-dev

image:generic_tests:
  extends: .build_except_kali-experimental

image:aptly:
  extends: .build_only_kali-dev

#
# Trigger build of other releases.
#
trigger other releases:
  extends: .trigger_build
  variables:
    RELEASES_LIST: 'kali-experimental kali-rolling'
