# Copyright salsa-ci-team and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.

include:
 - .images-ci.yml

variables:
  VENDOR: kali
  RELEASE: kali-dev
  BASE_IMAGE: "debian:testing"

.build_only_kali-dev: &build_only_kali-dev
  extends: .build_template
  only:
    variables:
      - $RELEASE == 'kali-dev'

#
# These images build only for kali-dev.
#
image:aptly:
  extends: .build_only_kali-dev

image:autopkgtest:
  extends: .build_only_kali-dev

image:blhc:
  extends: .build_only_kali-dev

image:gbp:
  extends: .build_only_kali-dev

image:piuparts:
  extends: .build_only_kali-dev

image:reprotest:
  extends: .build_only_kali-dev

#
# These images build for all the releases.
#
image:base:
  extends: .build_template

image:i386/base:
  extends: .build_template
  variables:
    ARCH: 'i386'

image:lintian:
  extends: .build_template
  only:
    variables:
      # Use != to avoid overriding template except.
      - $RELEASE != 'kali-experimental'

image:generic_tests:
  extends: .build_template

#
# Trigger build of other releases.
#
trigger other releases:
  extends: .trigger_build
  variables:
    RELEASES_LIST: 'kali-experimental kali-rolling'
