# Copyright salsa-ci-team and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.

.build_kali_base:
  extends: .build_base
  variables:
    VENDOR: kali
    BASE_IMAGE: "debian:testing"

.build_kali_others:
  extends: .build_others
  variables:
    VENDOR: kali

base:kali-rolling:
  extends: .build_kali_base

base:kali-dev:
  extends: .build_kali_base

base:kali-experimental:
  extends: .build_kali_base

piuparts:kali-dev:
  extends: .build_kali_others

reprotest:kali-dev:
  extends: .build_kali_others

autopkgtest:kali-dev:
  extends: .build_kali_others

blhc:kali-dev:
  extends: .build_kali_others

lintian:kali-rolling:
  extends: .build_kali_others

lintian:kali-dev:
  extends: .build_kali_others

gbp:kali-dev:
  extends: .build_kali_others

dockerbuilder:kali-rolling:
  extends: .build_kali_others

dockerbuilder:kali-dev:
  extends: .build_kali_others

dockerbuilder:kali-experimental:
  extends: .build_kali_others

generic_tests:kali-rolling:
  extends: .build_kali_others

generic_tests:kali-dev:
  extends: .build_kali_others

aptly:kali-dev:
  extends: .build_kali_others
