# Copyright salsa-ci-team and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
---
stages:
  - build

.build_template: &build_template
  stage: images
  image:
    name: debian:trixie-slim
  before_script:
    - apt-get update ; apt-get -y install buildah ca-certificates wget
    - buildah login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY_IMAGE}"
  retry:
    max: 1
    when:
      - script_failure
  script:
    - cd images
    - |
      # If not master, use REF as staging tag.
      if ! [ "${CI_COMMIT_REF_NAME}" = "master" ]; then
        STAGING_TAG="_${CI_COMMIT_REF_SLUG}"
      fi
    - |
      # Set BASE_IMAGE, unless already set.
      if [ -z "${BASE_IMAGE}" ]; then
        case "${VENDOR}" in
          kali) BASE_IMAGE=${RELEASE}:${ARCH} ;;
          *)    BASE_IMAGE=${VENDOR}:${RELEASE} ;;
        esac
      fi
    - |
      # Set REGISTRY_NAMESPACE where BASE_IMAGE exists.
      case "${VENDOR}" in
        kali) REGISTRY_NAMESPACE=kalilinux ;;
        # The `library` namespace is where Docker official images reside
        # regardless of their architecture.
        *)    REGISTRY_NAMESPACE=library ;;
      esac
    - |
      # Use "arm32v5" namespace for Bullseye ARM/V5 image because this image
      # doesn't currently exist on Docker registry's "library" namespace.
      # Remove this part when the cause of it's existence no longer relevant.
      if [ "${RELEASE}" = "bullseye" ] && [ "${ARCH}" = "arm/v5" ]; then
        REGISTRY_NAMESPACE=arm32v5
      fi
    - IMAGE_NAME_WITH_TAG=${IMAGE_NAME}:${RELEASE}${STAGING_TAG}
    - |
      # Non-amd64 images have their own namespace
      if [ "${ARCH}" != "amd64" ]; then
        ARCH_NAMESPACE=${ARCH}/
      fi
    - |
      # Salsa CI uses a different architecture naming scheme for the ARCH_NAMESPACE
      # variable than the one used to specify image architecture pulled from
      # Docker official container registry.
      case "${ARCH}" in
        arm/v5) ARCH_NAMESPACE=arm32v5/ ;;
        arm/v7) ARCH_NAMESPACE=arm32v7/ ;;
        arm64/v8) ARCH_NAMESPACE=arm64v8/ ;;
      esac
    - IMAGE_URL=${CI_REGISTRY_IMAGE}/${ARCH_NAMESPACE}${IMAGE_NAME_WITH_TAG}
    - |
      # Render Containerfile.
      cat $(ls -v containerfiles/base.*) > Containerfile
      if ! [ "${IMAGE_NAME}" = "base" ]; then
        cat $(ls -v containerfiles/$IMAGE_NAME.*) >> Containerfile
      fi
    - |
      # Check if aliases are needed.
      if [ "${CI_COMMIT_REF_NAME}" = "master" ]; then
        case "$VENDOR" in
          debian)
            case "$RELEASE" in
              stretch)
                MIRROR=${DEBIAN_ARCHIVE_MIRROR}
              ;;
              *)
                MIRROR=${DEBIAN_MIRROR}
              ;;
            esac
            ALIASES=$(wget -O - ${MIRROR}/dists/${RELEASE}/Release | awk "/^Suite:/ { if (\$2 !~ /${RELEASE}/) print \$2 }")
            test "$ALIASES" != 'unstable' || ALIASES="${ALIASES} latest"
            # autopkgtest image is built on top of stable. Let's make the
            # latest tag an alias of it.
            test "$IMAGE_NAME" != 'autopkgtest' || ALIASES="${ALIASES} latest"
          ;;
          kali)
            test "$RELEASE" != "kali-dev" || ALIASES="${ALIASES} latest"
          ;;
        esac
      fi
    # TOOD: test using cache. We had some issues with the cache used by kaniko.
    # See 7788516d, but we could give it a try with buildah.
    - |
      buildah build \
        --file ${PWD}/Containerfile \
        --build-arg VENDOR=${VENDOR} \
        --build-arg RELEASE=${RELEASE} \
        --build-arg BASE_IMAGE=${BASE_IMAGE} \
        --build-arg REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE} \
        --arch "${ARCH}" \
        --tag ${IMAGE_NAME_WITH_TAG}
    - buildah push ${IMAGE_NAME_WITH_TAG} ${CI_REGISTRY_IMAGE}/${ARCH_NAMESPACE}${IMAGE_NAME_WITH_TAG}
    - |
      for ALIAS in ${ALIASES}; do
        ALIAS_WITH_TAG=${IMAGE_NAME}:${ALIAS}${STAGING_TAG}
        buildah push ${IMAGE_NAME_WITH_TAG} ${CI_REGISTRY_IMAGE}/${ARCH_NAMESPACE}${ALIAS_WITH_TAG}
      done
  after_script:
    - buildah logout "${CI_REGISTRY_IMAGE}"
