# Copyright salsa-ci-team and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.

include:
 - salsa-ci.yml
 - pipeline-jobs.yml

check license + contributor:
    stage: contributions
    image: ${SALSA_CI_IMAGES_BASE}
    dependencies: []
    before_script:
        - apt-get update && apt-get install -y licensecheck
    script:
        # check files without any license
        - bash -c "exit $(licensecheck -r . | grep -Ev '(images/files)|(images/patches)|(README.md)|(CONTRIBUTORS)' | grep UNKNOWN | wc -l)"
        # check email is in the list of contributors
        - grep ${GITLAB_USER_EMAIL} CONTRIBUTORS

clone:
    stage: clone
    image: debian:unstable
    before_script:
        - echo "I need to skip before_script"
    artifacts:
      paths:
          - repo_test
    script:
        - apt-get update && apt-get install git -y
        - git clone https://salsa.debian.org/salsa-ci-team/dummypackage repo_test

before_script:
    - cd repo_test
